### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by bsr203** [Drathal/react-playground#4]
I never set it up before but tried your setup. It shows 100% coverage, but when I remove a test, it still shows the same. Is it working for you? may be we need to include source files apart form tests with [include](https://www.npmjs.com/package/nyc#including-files) Let me know. thanks.

**Comment by Drathal** [comment]
I had a bug in the coverage config. I used a non working glob to specify what files should be excluded. That is no fixed with commit fdf7156ea47b6b6d69a0b63577444a34b2b1b104 
Thanks again for reporting it 👍

**Comment by bsr203** [comment]
thanks. going to try out and report back shortly. just got up :-)

**Comment by bsr203** [comment]
sorry, forgot to close. indeed it works great now. thanks.
